feat:login-endpiont
SheyiB/Mock-Bank-API pull request #2
Opened 2024-04-18 15:50 UTC by EseigbeSamuel

2024-04-18 15:53 UTC, EseigbeSamuel commented
login endpoint

2024-04-19 17:18 UTC, SheyiB commented
> login endpoint

@EseigbeSamuel Great work! I'm impressed! Keep it up!

2024-04-19 17:20 UTC, SheyiB requested changes

2024-04-19 17:20 UTC, SheyiB commented on src/services/auth.service.js
> +      let user = await this.model.findOne({
@EseigbeSamuel can you improve this so we first check for the email and if the email is not found we send a message. After doing that we then check for the password, but remember we created a password match method on customer model that is what we use to check if passwords match. Let me know if you have questions. Great work! Well done

2024-04-21 19:41 UTC, SheyiB approved these changes
Great Work! Super Impressive

2024-04-21 19:41 UTC, merged